# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/

      - name: Install vercel
        run: npm install
        env:
          CI: true

      - name: Install studio
        run: cd studio && npm ci
        env:
          CI: true

      - name: Install web
        run: cd web && npm ci
        env:
          CI: true

      - name: Deploy gql
        run: cd studio && npm run gql:ci
        env:
          CI: true
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}

      - name: Deploy studio
        run: cd studio && npm run deploy
        env:
          CI: true
          SANITY_READ_DATA_TOKEN: ${{ secrets.SANITY_READ_DATA_TOKEN }}

      - name: Build and deploy web
        run: vercel --prod --token $VERCEL_TOKEN_ALT
        env:
          CI: true
          SANITY_READ_DATA_TOKEN: ${{ secrets.SANITY_READ_DATA_TOKEN }}
          VERCEL_TOKEN_ALT: ${{ secrets.VERCEL_TOKEN_ALT }}
