# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://registry.npmjs.org/

      - name: Install studio
        run: cd studio && npm install
        env:
          CI: true

      - name: Install web
        run: cd web && npm install
        env:
          CI: true

      - name: Deploy gql
        run: cd studio && npm run gql:ci
        env:
          CI: true

      - name: Build web
        run: cd web && npm run build
        env:
          CI: true
